### ISSUE TITLE
two issues in development-branch

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#11]
I know it's the development-branch but here are two issues:

-  token.js is referenced but does not exist in the branch.
- default address of VAMP is set to port 3000 (most easy way to reproduce is starting a incognito-window and surfing to localhost:3000)

**Comment by danielsneijers** [comment]
The token.js file indeed seems to be missing, will add a patch for this to the release. Regarding the default address: it takes your window.location as a default, mainly because most people will be running the UI from the complete VAMP package. For instance: if you use the vamp-docker setup from the tutorial on vamp.io, your UI endpoint would be 192.168.59.103:8080, and the API endpoint would be 192.168.59.103:8080/api/v1. The option to change the endpoint of the UI was build in to ensure people running the standalone build of the UI have the flexibility to use each endpoint they like.

**Comment by JoshFalken** [comment]
@danielsneijers: clear, thanks for the clarification! Still a small point though, when you change the address of the 'rest api url', you don't get any visual feedback that the UI is probing that address. Maybe add a button to update the address? Or add a status line below VAMP the version to give the status of the UI?

**Comment by brniamut** [comment]
In the 0.9.0 release the first issue will be fixed it will then also be possible to set the api endpoint with a script. How the script works will be described in the documentation. With these remarks I consider the issue closed. Just hold until the new release and all you wishes will come true :P

If you have other remarks concerning this issue, feel free to reopen it.
