### ISSUE TITLE
show up/down trend indicator errors with scale parameters

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#112]
f.e. when number of instances is going up or down, a green up arrow, or a red down arrow would give a good indication of a trend going on. Open for better alternatives of course :)

**Comment by dragoslav** [comment]
sparkline? if we have sparkline implementation for metrics/health, adding here should be simple.

**Comment by brniamut** [comment]
Personally I would use the arrow solution. Just because it looks better. I would suggest doing this after issue #68 is closed. 

This issue would then make use of the same directive as used in #110. As noted in issue #110 this is much easier to solve if the datahandeling is refactored. It would require 4 changed lines in the directive for it to work. See also stackoverflow http://stackoverflow.com/a/23965917.

**Comment by dragoslav** [comment]
One problem I see in current implementation (it's not a bug) is that when you change number of instances (or use a background workflow), scale changes (request accepted) but number of actual instances will be updated only when change is finalized (e.g. Marathon).
Asking for 2 and after few seconds that will happen, meanwhile it can be confusing:

![screen shot 2016-09-29 at 11 20 08](https://cloud.githubusercontent.com/assets/7957524/18948687/5dd364b4-8638-11e6-92c5-1ca0839a4dc3.png)

I would add an arrow (up/down) in instances column, when a scale request is accepted but we still wait for action to complete. If in given example we see an up arrow, it's clear why there is a discrepancy between scale instances value and actual number of instances.

**Comment by olafmol** [comment]
we need to answer: what is the relevant information we want to communicate to a devops team-member that's using the UI and looking at the scale. Is it historic patterns (i.e. graph) or is it trend (i.e. arrow)?

**Comment by dragoslav** [comment]
Highlighting instances if their number is different than in scale.
