### ISSUE TITLE
List view action buttons design

### ISSUE THREAD

**Issue by eyal-magnetic** [magneticio/vamp-ui#204]
Relates to #182 and #177

Need a design for list view for Aritfacts with actions (deployments, workflows, blueprints)

Currently the functionality is accessible through this design:
![image](https://cloud.githubusercontent.com/assets/24912601/22102447/c7ac7356-de37-11e6-8ecd-daf57bca5922.png)

Need @DHVAMP to define and design where and how to display the actions.

**Comment by DHVAMP** [comment]
Instead of going with icon buttons I would prefer to go with text based buttons. mainly because we have 'odd' actions like export to blueprint etc. I would also prefer the ghost buttons on the list items. I would like to hear your opinion on this matter. 

![list-action-buttons](https://cloud.githubusercontent.com/assets/20397075/22106995/cf04766c-de4b-11e6-8b7c-6afe18a6a23c.png)
