### ISSUE TITLE
admin > backend configuration edit mode is empty

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#247]
when editing the backend configuration screen it shows an empty editor. Only after pasting a complete configuration and saving this it is displayed after editing.

<img width="1010" alt="screen shot 2017-02-04 at 00 09 16" src="https://cloud.githubusercontent.com/assets/355268/22612172/305fe3fe-ea6f-11e6-960d-1ec76a693310.png">

**Comment by dragoslav** [comment]
One solution:
- `applied` is editable, if saved then it's stored as `dynamic` (low level API) - no `dynamic` tab at all

Another:
- we keep `dynamic` tab (similar to PoC) and only `dynamic` values are editable
- `dynamic` should be renamed based on key-value type (from the info message), e.g. `dynamic (zookeeper)` or just `zookeeper`

This solution is better because:
- there is no higher level magic 
- it's clear that new configuration is persisted between restarts and where it is stored
- it fits well with current documentation and further updates http://vamp.io/documentation/installation/configure-vamp/ (what is reference, application ... and now dynamic/key-value)
- there is no need to store full configuration in key-value store but just what is needed (snippet), e.g. why to expose potentially confidential settings
- it's possible to go back and forth between `dynamic` and others (e.g. applied) in order to copy/paste/modify and afterwards save

**Comment by olafmol** [comment]
related to #264
