### ISSUE TITLE
when deploying using existing gateway port no UI warning is shown

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#377]
when having a deployment running on a specific external gateway (f.e. 9050) or only having a gateway there, and then deploying a new blueprint with an inline gateway definition on this same port, the UI shows or does nothing when clicking deploy-as, but in the Vamp logs it says:

[0;39m[36m15:31:40.372[0;39m [1;31m| ERROR | io.vamp.common.notification.Notification |                                          | Gateway port 'Some(9050)' is/was in use by deployment: 'sava/9050'. Remove 'sava/9050' gateway first or use different port.
[0;39m

**Comment by ThomasMeijers** [comment]
Fixed by 6bc5556.  The toaster error is now shown before the modal, if you try to deploy a Blueprint with a port that's already in use by another Blueprint. If it's the same Blueprint to deploy, then the modal is shown and the toaster message after trying to deploy, since the user can also choose for a merge of the Blueprint.
