### ISSUE TITLE
Consistent artifact representation in lists

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#47]
- deployments and gateways are clickable, but other not. 
- there is `edit` for gateways but not for deployments

One approach would be:

- all artifacts are clickable and that means the whole row
- for deployment and gateways we go to overview page, for other `edit` page
- we should have `edit` for every type, or just on deployment/gateway overview `edit` - this is needed because there are thing not available in overview (e.g. balance, virtual hosts) and we still should allow editing - and this keeps UI forward compatible (no need to update overview after every new feature)

**Comment by brniamut** [comment]
Well we should define what is editing. 

Let's take gateways for example. 

- You can click on one and you get a view of the single gateways. There you can edit things. Things like, weights, conditions, condition-strength. 
- You can also click on the edit button in the overview and edit the YAML that is present there.

So you can edit in the single-overview or the list. Those are both edits. My suggestion would be that you would always go to single-overview where you can edit individual parameters. Then there should always be a "Edit in YAML/JSON" option on that page so that you can do it that way.

Benefits are there is one page where all editing takes place and the user will understand that editing is editing. There is no difference in selecting something from a dropdown or just editing it in the YAML representation.

**Comment by dragoslav** [comment]
@brniamut , is the current navigation consistent?

**Comment by brniamut** [comment]
Again it depends on what you call consistent. Clicking an an entity bring you to page with more information about that entity. Clicking on the edit button let's you go to a page where you can edit the entity. So imo that is consistent.
