### ISSUE TITLE
Deployment page - show service environment variables

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#52]
Service level (not breed level) environment variables.

**Comment by brniamut** [comment]
![screenshot 2016-08-17 14 47 11](https://cloud.githubusercontent.com/assets/2960616/17736730/bd9f0c7a-6489-11e6-9439-799bde2439c2.png)

@dragoslav @olafmol 

I will close this issue for now because the functionality is there. But we need to think about the design a little bit. As you can see there is too much info to cramp in a horizontal space.
