### ISSUE TITLE
Blueprints not refreshed

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp-ui#6]
Sometimes when I add a blueprint, the blueprint-page isn't automatically refreshed. To reproduce:

- Add a blueprint (using add new on the blueprints page)
- Delete the blueprint (using delete on the blueprints page)
- Add a blueprint (using add new on the blueprints page)

**Comment by danielsneijers** [comment]
Hi Josh,

Great discovery, a scenario which I didn't encounter before. It had to do with the way React.js calculates how a page should be rendered: all DOM elements require a unique id, which in this case was based on the name of the blueprint. Since we were adding the blueprint with the same name multiple times it didn't understand it was a new item, not the previously deleted one. Fixed this in the development branch, it will be included in the next release.

**Comment by JoshFalken** [comment]
@danielsneijers : great! And thanks for explanation!
