### ISSUE TITLE
Instead of deployment service gateways, show ports?

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#61]
Maybe it would be better to have column `Ports` and when it's clicked on of them you go to gateway. Gateways are defined on cluster level not service level. Service corresponds to route.

**Comment by brniamut** [comment]
![screenshot 2016-08-17 14 47 11](https://cloud.githubusercontent.com/assets/2960616/17736851/42680dbc-648a-11e6-9012-8db5b5d4639a.png)

As you can see the gateways now have ports besides them. So the difference is clear. I understand the issue though. Because you would like the gateway to be on cluster level. This needs some rethinking about the UI/UX in which we take on the whole screen.

There is so much info to be displayed on one screen that everything get't very cluttered. Also where do I display the clusterinfo, labels for the services and the info of the services themself. All these elements need to be included in a clean design.

**Comment by dragoslav** [comment]
Breeds (services) may have ports defined, e.g. `web` and `health` (in above example it's `port`). Instead of showing `deployment/cluster/web` and `deployment/cluster/health` why not just only `web` and `health` in column `Ports`? You define ports and ports are materialized as gateway routes.

**Comment by olafmol** [comment]
i agree. Lets give the column-label the name "Ports" and simply show the name of the port, and make it clickable to jump to the specific gateway detail screen. We can add an additional Cluster-related table above the service(s) rows where we can display the gateway (clickable) and other cluster-related metrics/graphs.
