### ISSUE TITLE
In gateway detail screen show realtime sparklines for every route

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#67]
the realtime sparklines for every route should be: health, rate, latency

**Comment by dragoslav** [comment]
Since e7e4d1d97f7919e89570b3a21d0aeaa4323e8a2e:

- health charts are broken, before there was a refresh on update
- this refresh is now introduced to metrics charts
- metrics charts don't need to be updated every 25ms (40 times / sec)
- update of http://jtblin.github.io/angular-chart.js/ chart works fine, example code https://github.com/jtblin/angular-chart.js/blob/gh-pages/examples/app.js
