### ISSUE TITLE
deployment and gateway detail screens open streams but never close them

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#77]
when going to the deployment or gateway detail screen a stream is openen but never closed again. When switching multiple times to detail screens there are multiple stream connections open that "choke" any other request to the backend. Requesting info directly to the API seems to clean up open streams and the system "unclogs" and becomes responsive again. 

It would be nice if we can detect this situation of to many open network streams so we can provide some kind of message in the UI when this happens for whatever reason (ie bugs)

**Comment by brniamut** [comment]
There of course should be only on stream running at all times for the [stream] endpoint. Having more then one stream running for the same data is overkill. Because there is always a stream running anyways (for the all events panel) we don't even need to open a different stream for other tags. This was a design error. 

Can be fixed by filtering on tags on the frontend making everything much quicker.

**Comment by brniamut** [comment]
Only one stream is running now. Makes the platform much more stable!
