### ISSUE TITLE
Show deployment content

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#78]
currently there seems to be no way to see the content of a running deployment. Especially after merging this would be very helpful to have a view deployment option. this is also related to save as blueprint functionality #34

**Comment by brniamut** [comment]
There is now an edit button users can click on to see the YAML content of a running deployment. See issue #113. 

If you want a view where you can only read the YAML we should look for a way to include that in the UI. Because then you have a YAML view and a details view which represent the same data in an other way.

For now I consider this issue resolved because issue #113 makes the functionality available. Please reopen if this is not the case.
