### ISSUE TITLE
Missing icon for info panel

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-ui#99]

**Comment by brniamut** [comment]
![screenshot 2016-08-18 13 50 56](https://cloud.githubusercontent.com/assets/2960616/17772759/d55b9efc-654a-11e6-8d15-3c5624368217.png)

Try to rebuild.

**Comment by dragoslav** [comment]
Yes and still in Firefox, Chrome and Safari.

**Comment by brniamut** [comment]
I tried it again, can't reproduce the error. This with a whole new clone, build, and start of the quick-start. Maybe when you are back I can see it on your system. @olafmol does this error occur on your machine?

**Comment by olafmol** [comment]
I do see an I icon, but i also see these 404 errors appear in my browser after loading the UI:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontawesome-webfont.svg, line 0)

http://192.168.99.100:8080/fonts/fontawesome-webfont.woff?v=4.6.3
http://192.168.99.100:8080/fonts/fontawesome-webfont.ttf?v=4.6.3
http://192.168.99.100:8080/fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular

**Comment by dragoslav** [comment]
Also button icons: <img width="1379" alt="screen shot 2016-08-18 at 17 56 50" src="https://cloud.githubusercontent.com/assets/7957524/17780914/64eab658-656d-11e6-8d5c-0433c2d88c3a.png">

**Comment by olafmol** [comment]
I can confirm this, in Firefox it happens (in safari and chrome i see the icons). In firefox i see the following error: 
<img width="1250" alt="screen shot 2016-08-18 at 18 06 38" src="https://cloud.githubusercontent.com/assets/355268/17781251/e214ec60-656e-11e6-8e7a-3642134dedce.png">

**Comment by brniamut** [comment]
Aaah okay guys. Let me see what is going on. Thanks for the research work

**Comment by brniamut** [comment]
As you can see it is an unique error:

https://github.com/cdnjs/cdnjs/issues/755

Possible fixes named:

Change the .htpaccess file to give it the good rights. I assume gulp servers the webpage when it build locally. So I will first find out how to do there.

An other comment suggests using an absolute path. In my understanding the gulp script already converts everything to absolute paths but I also will give that one a try.

The last comment suggests this is a Firefox issue and using css pseudoelements to insert icons. I really **really** hope it isn't that one because that would be one hell of a bug. I'm not inclined to belive that one because it would mean a whole lot of sites on the interent would have no icons when using firefox.

**Comment by dragoslav** [comment]
I have the same problem using all 3 browsers - previous screen shot is from Chrome.
